In [1]:
from __future__ import print_function
from keras.models import Sequential
from keras import layers
import numpy as np
from six.moves import range

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
# recursive
def bin(n):
    if n > 1: 
        bin(n // 2) 
          
    #print(n % 2, end = "")
    print(n & 1, end = "")

In [3]:
bin(333)

101001101

In [4]:
bin(333 + 333)

1010011010

In [5]:
format(999, 'b'), len(format(999, 'b'))

('1111100111', 10)

In [6]:
format(9999, 'b'), len(format(9999, 'b'))

('10011100001111', 14)

In [7]:
list('10011100001111')

['1', '0', '0', '1', '1', '1', '0', '0', '0', '0', '1', '1', '1', '1']

In [8]:
b = list('10011100001111')
value = 0
for i in range(len(b)):
    digit = b.pop()
    if digit == '1':
        value = value + pow(2, i)
print("The decimal value of the number is", value)

The decimal value of the number is 9999


In [9]:
list(range(10, -1, -1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [10]:
class BinaryRepresentation():

    def encode(self, C, num_digits):
        """binary string representatio of integer C, padded up to num_digits digits
        """
        b = format(C, 'b')
        return (num_digits - len(b)) * '0' + b

    def decode(self, x):
        """Decode the given binary string to its decimal representation
        """
        b = list(x)
        value = 0
        for i in range(len(b)):
            digit = b.pop()
            if digit == '1':
                value = value + pow(2, i)
        return value
    
    def decode_tf(self, x):
        """Decode the given binary boolean array to its decimal representation
        """
        value = 0
        l = list(x)
        for i in range(len(l)):
            digit = l.pop()
            if digit == True:
                value = value + pow(2, i)
        return value
    
#     def decode_ttf(self, x):
#         """Decode the given binary boolean array to its decimal representation
#         """
#         value = 0
#         l = list(x)
#         for i in range(len(l)):
#             digit = l[i][0]
#             if digit == True:
#                 value = value + pow(2, len(l)-1-i)
#         return value

class colors:
    ok = '\033[92m'
    fail = '\033[91m'
    close = '\033[0m'

In [11]:
br = BinaryRepresentation()

In [12]:
br.encode(123, 14)

'00000001111011'

In [13]:
br.decode('00000001111011')

123

In [14]:
tf_123 = [True if '1'==c else False for c in '00000001111011']
print(tf_123)
br.decode_tf(tf_123)

[False, False, False, False, False, False, False, True, True, True, True, False, True, True]


123

In [15]:
''.join(np.random.choice(list('0123456789')))

'9'

In [16]:
int(''.join(np.random.choice(list('0123456789')) for i in range(np.random.randint(1, 4))))

5

In [17]:
# Parameters for the model and dataset.
TRAINING_SIZE = 50000
DIGITS = 3
REVERSE = False

# Maximum length of input is 'int + int' (e.g., '34+78  '). Maximum length of
# int is DIGITS.
MAXLEN = DIGITS + 1 + DIGITS

# All the numbers, plus sign and space for padding.
#chars = '0123456789+ '
#ctable = CharacterTable(chars)

questions = []
expected = []
seen = set()
print('Generating data...')
while len(questions) < TRAINING_SIZE:
    f = lambda: int(''.join(np.random.choice(list('0123456789'))
                    for i in range(np.random.randint(1, DIGITS + 1))))
    a, b = f(), f()
    # Skip any addition questions we've already seen
    # Also skip any such that x+Y == Y+x (hence the sorting).
    key = tuple(sorted((a, b)))
    if key in seen:
        continue
    seen.add(key)
    
    query = (br.encode(a,16), br.encode(b,16))
    ans = br.encode(a + b, 16)

    questions.append(query)
    expected.append(ans)
    print(query, ans)
print('Total addition questions:', len(questions))

Generating data...
('0000000001001101', '0000000001001101') 0000000010011010
('0000000001011011', '0000001101111100') 0000001111010111
('0000000000000001', '0000000000000010') 0000000000000011
('0000000000000000', '0000000000001001') 0000000000001001
('0000000000001001', '0000000101100110') 0000000101101111
('0000000000100001', '0000000000001001') 0000000000101010
('0000000001001111', '0000000000000111') 0000000001010110
('0000000000000010', '0000000000000111') 0000000000001001
('0000000000000111', '0000000000100111') 0000000000101110
('0000000000001000', '0000000111111100') 0000001000000100
('0000000000000110', '0000000000001001') 0000000000001111
('0000000000010100', '0000001000101001') 0000001000111101
('0000001010111000', '0000000001010110') 0000001100001110
('0000000001000010', '0000000000000101') 0000000001000111
('0000000000111001', '0000000001010111') 0000000010010000
('0000000000010101', '0000000000110010') 0000000001000111
('0000000000000110', '0000000000101010') 000000000011

In [18]:
questions

[('0000000001001101', '0000000001001101'),
 ('0000000001011011', '0000001101111100'),
 ('0000000000000001', '0000000000000010'),
 ('0000000000000000', '0000000000001001'),
 ('0000000000001001', '0000000101100110'),
 ('0000000000100001', '0000000000001001'),
 ('0000000001001111', '0000000000000111'),
 ('0000000000000010', '0000000000000111'),
 ('0000000000000111', '0000000000100111'),
 ('0000000000001000', '0000000111111100'),
 ('0000000000000110', '0000000000001001'),
 ('0000000000010100', '0000001000101001'),
 ('0000001010111000', '0000000001010110'),
 ('0000000001000010', '0000000000000101'),
 ('0000000000111001', '0000000001010111'),
 ('0000000000010101', '0000000000110010'),
 ('0000000000000110', '0000000000101010'),
 ('0000000000001111', '0000001100101111'),
 ('0000000001000100', '0000000001010010'),
 ('0000000000111011', '0000000000000110'),
 ('0000000000000100', '0000000000100100'),
 ('0000001011101100', '0000000000100010'),
 ('0000001011000101', '0000001011111101'),
 ('00000000

In [19]:
expected

['0000000010011010',
 '0000001111010111',
 '0000000000000011',
 '0000000000001001',
 '0000000101101111',
 '0000000000101010',
 '0000000001010110',
 '0000000000001001',
 '0000000000101110',
 '0000001000000100',
 '0000000000001111',
 '0000001000111101',
 '0000001100001110',
 '0000000001000111',
 '0000000010010000',
 '0000000001000111',
 '0000000000110000',
 '0000001100111110',
 '0000000010010110',
 '0000000001000001',
 '0000000000101000',
 '0000001100001110',
 '0000010111000010',
 '0000000001001100',
 '0000000001011101',
 '0000001111011010',
 '0000010111001111',
 '0000000001110100',
 '0000001111001001',
 '0000001110010001',
 '0000001101001010',
 '0000000001111110',
 '0000001101101001',
 '0000000001111010',
 '0000000000001101',
 '0000000000011010',
 '0000001011111110',
 '0000000000011011',
 '0000000010101010',
 '0000000100001101',
 '0000001110101011',
 '0000000000101001',
 '0000000001001100',
 '0000001010001010',
 '0000000011100000',
 '0000001011010010',
 '0000000010011101',
 '00000000010

In [20]:
print('Vectorization...')
x = np.zeros((len(questions), 19), dtype=np.bool)
y = np.zeros((len(questions), 19), dtype=np.bool)
z = np.zeros((len(questions), 19), dtype=np.bool)

for i, (q, a) in enumerate(zip(questions,expected)):
    for j,c in enumerate(q[0]):
        if '1' == c: x[i][j] = True
    for j,c in enumerate(q[1]):
        if '1' == c: y[i][j] = True
    for j,c in enumerate(a):
        if '1' == c: z[i][j] = True
        
x[0], y[0], z[0]

Vectorization...


(array([False, False, False, False, False, False, False, False, False,
         True, False, False,  True,  True, False,  True, False, False,
        False]),
 array([False, False, False, False, False, False, False, False, False,
         True, False, False,  True,  True, False,  True, False, False,
        False]),
 array([False, False, False, False, False, False, False, False,  True,
        False, False,  True,  True, False,  True, False, False, False,
        False]))

In [21]:
questions[0], expected[0]

(('0000000001001101', '0000000001001101'), '0000000010011010')

In [22]:
list(x[0])

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False]

In [23]:
print('Vectorization...')
x = np.zeros((len(questions), 2, 16), dtype=bool)
y = np.zeros((len(questions), 16), dtype=bool)

for i, (q, a) in enumerate(zip(questions,expected)):
    for j,c in enumerate(q[0]):
        if '1' == c: x[i][0][j] = True
    for j,c in enumerate(q[1]):
        if '1' == c: x[i][1][j] = True
    for j,c in enumerate(a):
        if '1' == c: y[i][j] = True
        
x[0], y[0]

Vectorization...


(array([[False, False, False, False, False, False, False, False, False,
          True, False, False,  True,  True, False,  True],
        [False, False, False, False, False, False, False, False, False,
          True, False, False,  True,  True, False,  True]]),
 array([False, False, False, False, False, False, False, False,  True,
        False, False,  True,  True, False,  True, False]))

In [24]:
br.decode_tf(x[0][0]), br.decode_tf(x[0][1])

(77, 77)

In [25]:
br.decode_tf(y[0])

154

In [26]:
print('Vectorization...')
x = np.zeros((len(questions), 2, 16), dtype=bool)
y = np.zeros((len(questions), 1, 16), dtype=bool)

for i, (q, a) in enumerate(zip(questions,expected)):
    for j,c in enumerate(q[0]):
        if '1' == c: x[i][0][j] = True
    for j,c in enumerate(q[1]):
        if '1' == c: x[i][1][j] = True
    for j,c in enumerate(a):
        if '1' == c: y[i][0][j] = True
        
x[0], y[0]

Vectorization...


(array([[False, False, False, False, False, False, False, False, False,
          True, False, False,  True,  True, False,  True],
        [False, False, False, False, False, False, False, False, False,
          True, False, False,  True,  True, False,  True]]),
 array([[False, False, False, False, False, False, False, False,  True,
         False, False,  True,  True, False,  True, False]]))

In [27]:
print('Vectorization...')
x = np.zeros((len(questions), 2, 16), dtype=bool)
y = np.zeros((len(questions), 1, 16), dtype=bool)

for i, (q, a) in enumerate(zip(questions,expected)):
    for j,c in enumerate(q[0]):
        if '1' == c: x[i][0][j] = True
    for j,c in enumerate(q[1]):
        if '1' == c: x[i][1][j] = True
    for j,c in enumerate(a):
        if '1' == c: y[i][0][j] = True

Vectorization...


In [28]:
x[0]

array([[False, False, False, False, False, False, False, False, False,
         True, False, False,  True,  True, False,  True],
       [False, False, False, False, False, False, False, False, False,
         True, False, False,  True,  True, False,  True]])

In [29]:
br.decode_tf(x[0][0]), br.decode_tf(x[0][1])

(77, 77)

In [30]:
y[0]

array([[False, False, False, False, False, False, False, False,  True,
        False, False,  True,  True, False,  True, False]])

In [31]:
# Shuffle (x, y) in unison as the later parts of x will almost all be larger
# digits.
indices = np.arange(len(y))
np.random.shuffle(indices)
x = x[indices]
y = y[indices]

# Explicitly set apart 10% for validation data that we never train over.
split_at = len(x) - len(x) // 10
(x_train, x_val) = x[:split_at], x[split_at:]
(y_train, y_val) = y[:split_at], y[split_at:]

print('Training Data:')
print(x_train.shape)
print(y_train.shape)
print()

print('Validation Data:')
print(x_val.shape)
print(y_val.shape)
print()

print('Example:')
print(x_train[0])
print(y_train[0])
print(br.decode_tf(x_train[0][0]))
print('+')
print(br.decode_tf(x_train[0][1]))
print('==')
print(br.decode_tf(y_train[0][0]))

Training Data:
(45000, 2, 16)
(45000, 1, 16)

Validation Data:
(5000, 2, 16)
(5000, 1, 16)

Example:
[[False False False False False False False False False False False  True
  False False False False]
 [False False False False False False False  True  True False  True  True
   True  True  True  True]]
[[False False False False False False False  True  True  True False False
   True  True  True  True]]
16
+
447
==
463


In [32]:
x_train.shape,y_train.shape

((45000, 2, 16), (45000, 1, 16))

In [33]:
# Try replacing GRU, or SimpleRNN.
RNN = layers.LSTM
HIDDEN_SIZE = 128
BATCH_SIZE = 128
LAYERS = 1

print('Build model...')
model = Sequential()
# "Encode" the input sequence using an RNN, producing an output of HIDDEN_SIZE.
# Note: In a situation where your input sequences have a variable length,
# use input_shape=(None, num_feature).
# New new new
model.add(RNN(HIDDEN_SIZE, input_shape=(2, 16)))
# As the decoder RNN's input, repeatedly provide with the last output of
# RNN for each time step. Repeat 'DIGITS + 1' times as that's the maximum
# length of output, e.g., when DIGITS=3, max output is 999+999=1998.
# New new new
model.add(layers.RepeatVector(1))
# The decoder RNN could be multiple layers stacked or a single layer.
for _ in range(LAYERS):
    # By setting return_sequences to True, return not only the last output but
    # all the outputs so far in the form of (num_samples, timesteps,
    # output_dim). This is necessary as TimeDistributed in the below expects
    # the first dimension to be the timesteps.
    model.add(RNN(HIDDEN_SIZE, return_sequences=True))

# Apply a dense layer to the every temporal slice of an input. For each of step
# of the output sequence, decide which character should be chosen.
model.add(layers.TimeDistributed(layers.Dense(16, activation='sigmoid')))
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['mse','binary_accuracy','accuracy'])
model.summary()

Build model...
Metal device set to: Apple M1
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 128)               74240     
_________________________________________________________________
repeat_vector (RepeatVector) (None, 1, 128)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 1, 128)            131584    
_________________________________________________________________
time_distributed (TimeDistri (None, 1, 16)             2064      
Total params: 207,888
Trainable params: 207,888
Non-trainable params: 0
_________________________________________________________________


2022-05-24 00:46:51.410522: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-24 00:46:51.410825: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [34]:
x_val[2]

array([[False, False, False, False, False, False, False,  True, False,
         True, False, False,  True, False,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True]])

In [35]:
ind = np.random.randint(0, len(x_val))
rowx, rowy = x_val[np.array([ind])], y_val[np.array([ind])]
n1 = br.decode_tf(rowx[0][0])
n2 = br.decode_tf(rowx[0][1])
n3 = br.decode_tf(rowy[0][0])
print(n1, n2, n3)

95 37 132


In [36]:
y_val

array([[[False, False, False, ...,  True, False,  True]],

       [[False, False, False, ...,  True,  True, False]],

       [[False, False, False, ...,  True, False, False]],

       ...,

       [[False, False, False, ..., False,  True,  True]],

       [[False, False, False, ...,  True, False, False]],

       [[False, False, False, ..., False,  True,  True]]])

In [ ]:
for iteration in range(1,50):
    print()
    print('-' * 50)
    print('Iteration', iteration)
    model.fit(x_train, y_train,
              batch_size=BATCH_SIZE,
              epochs=1,
              validation_data=(x_val, y_val))
    
    # Select 10 samples from the validation set at random so we can visualize
    # errors with green and red boxes
    for i in range(10):
        ind = np.random.randint(0, len(x_val))
        rowx, rowy = x_val[np.array([ind])], y_val[np.array([ind])]
        preds = model.predict(rowx)
        output = np.round(preds[0]).astype(int).tolist()[0]
        output_str = [str(x) for x in output]
        guess = br.decode(''.join(output_str))
#         preds = model.predict_classes(rowx, verbose=0)
        n1 = br.decode_tf(rowx[0][0])
        n2 = br.decode_tf(rowx[0][1])
        correct = br.decode_tf(rowy[0][0])
#         guess = preds
        print('Q:', n1, '+', n2, '==', correct, end=' ')
        if correct == guess:
            print(colors.ok + '☑' + colors.close, end=' ')
        else:
            print(colors.fail + '☒' + colors.close, end=' ')
        print(guess)


--------------------------------------------------
Iteration 1


2022-05-24 00:46:54.618304: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-05-24 00:46:54.618495: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-05-24 00:47:02.942749: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-05-24 00:47:03.060766: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2022-05-24 00:47:03.101011: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [ ]:
# evaluate the keras model
accuracy = model.evaluate(x_val, y_val)
# print('Accuracy: %.2f' % (accuracy*100))

In [ ]:
# evaluate the keras model
accuracy = model.evaluate(x_val, y_val)
# print('Accuracy: %.2f' % (accuracy*100))

In [ ]:
rowx = x_val[np.array([1])]
rowx

In [ ]:
f1 = br.encode(1023,16)

f2 = br.encode(1022,16)
print(f1,f2)
print('Vectorization...')
x = np.zeros((1,2, 16), dtype=bool)


for j,c in enumerate(f1):
    if '1' == c: x[0][0][j] = True
for j,c in enumerate(f2):
    if '1' == c: x[0][1][j] = True

preds = model.predict(x)
print(preds)
output = np.round(preds[0]).astype(int).tolist()[0]
output_str = [str(x) for x in output]
guess = br.decode(''.join(output_str))
print(guess)
print(br.encode(guess,16))

In [ ]:
x = np.random.randint(0, 100)
y = np.random.randint(0, 100)
z = x + y
print(x,y,z)
print()

x_plus_y_buffered = str(x) + '+' + str(y) + (9 - len(str(x) + '+' + str(y))) * ' '
x_plus_y_buffered

In [ ]:
z_buffered = str(z) + (5 - len(str(z))) * ' '
z_buffered

In [ ]:
x_plus_y_encoded = ctable.encode(x_plus_y_buffered, 9)
x_plus_y_encoded

In [ ]:
ctable.decode(x_plus_y_encoded)

In [ ]:
z_encoded = ctable.encode(z_buffered, 5)
z_encoded

In [ ]:
ctable.decode(z_encoded)

In [ ]:
x_plus_y = str(x) + '+' + str(y)
x_plus_y_tf = np.zeros((len(x_plus_y_buffered), len(chars)), dtype=bool)
x_plus_y_tf

In [ ]:
list(enumerate(x_plus_y_tf))

In [ ]:
ctable.encode('2', 1)

In [ ]:
for i, sentence in enumerate(x_plus_y_tf):
    x_plus_y_tf[i] = ctable.encode(x_plus_y_buffered[i], 1)
x_plus_y_tf

In [ ]:
z_tf = np.zeros((len(z_buffered), len(chars)), dtype=bool)
z_tf

In [ ]:
for i, sentence in enumerate(z_tf):
    z_tf[i] = ctable.encode(z_buffered[i], 1)
z_tf

In [ ]:
x_plus_y_tf2 = np.array((x_plus_y_tf, x_plus_y_tf), dtype=bool)
x_plus_y_tf2

In [ ]:
preds = model.predict_classes(x_plus_y_tf2, verbose=0)
preds

In [ ]:
ctable.decode(preds[0], calc_argmax=False)

In [ ]:
x = np.random.randint(0, 9999)
y = np.random.randint(0, 9999)
z = x + y
print(x,y,z)
print()

x_plus_y_buffered = str(x) + '+' + str(y) + (9 - len(str(x) + '+' + str(y))) * ' '
print('|' + x_plus_y_buffered + '|')
z_buffered = str(z) + (5 - len(str(z))) * ' '
print('|' + z_buffered + '|')

In [ ]:
x_plus_y_encoded = ctable.encode(x_plus_y_buffered, 9)
x_plus_y_tf = np.zeros((len(x_plus_y_buffered), len(chars)), dtype=bool)
for i, sentence in enumerate(x_plus_y_tf):
    x_plus_y_tf[i] = ctable.encode(x_plus_y_buffered[i], 1)

In [ ]:
z_encoded = ctable.encode(z_buffered, 5)
z_tf = np.zeros((len(z_buffered), len(chars)), dtype=bool)
for i, sentence in enumerate(z_tf):
    z_tf[i] = ctable.encode(z_buffered[i], 1)

# Prediction

In [ ]:
x_plus_y_tf2 = np.array((x_plus_y_tf, x_plus_y_tf), dtype=bool)
preds = model.predict_classes(x_plus_y_tf2, verbose=0)
ctable.decode(preds[0], calc_argmax=False)